# Generated by Django 5.1.1 on 2024-09-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("about", models.TextField(default="About This project.")),
                (
                    "description",
                    models.TextField(default="Description of this project."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Backstage", "Backstage"),
                            ("Planning", "Planning"),
                        ],
                        default="In Progress",
                        max_length=25,
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True,
                        default="2024-09-18 10:00:00",
                        null=True,
                        verbose_name="date published",
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        default="Python, Django, HTML, CSS, JS", max_length=255
                    ),
                ),
                ("image", models.FileField(blank=True, upload_to="project_images/")),
            ],
        ),
    ]
